name: Build and Release

permissions:
  "contents": "write"

on:
  pull_request:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-all:
    strategy:
      matrix:
        target:
          - "aarch64-apple-darwin"
          - "x86_64-apple-darwin"
          - "i686-unknown-linux-musl"
          - "x86_64-unknown-linux-musl"
          - "aarch64-unknown-linux-musl"
          - "x86_64-pc-windows-msvc"
          - "i686-pc-windows-msvc"
    name: Build For ${{ matrix.target }}
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
  release:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: product
          pattern: name-*
          merge-multiple: false
      - name: read CHANGELOG.md
        id: read
        run: |
          echo "TITLE=$(awk '/^#[^#]/{sub(/^# /, ""); print; exit}' CHANGELOG.md)" >> "$GITHUB_ENV"
          echo "$(awk '/^#[^#]/{if (flag) exit; flag=1; next} flag {if ($0 ~ /\S/) {print; found=1} else if (found) {print}}' CHANGELOG.md)" > body.txt
      - name: compress
        run: |
          cd product
          for dir in */; do
              dirname="${dir%/}"
              if [[ $dirname == *"windows"* ]]; then
                  echo "package $dirname to $dirname.zip"
                  zip -r "$dirname.zip" "$dirname"
              else
                  echo "package $dirname to $dirname.tar.gz"
                  tar -czf "$dirname.tar.gz" "$dirname"
              fi
          done
      - name: List Directory
        run: ls -R product
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.TITLE }}
          body_path: ./body.txt
          draft: false
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            ./product/*.zip
            ./product/*.tar.gz